# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/curriculum-tools

    docker:
      - image: circleci/node:8.9

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "node/package.json" }}
      - run:
          name: install npm
          command: cd node && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "node/package.json" }}
          paths:
            - node/node_modules
      # run tests!
      - run:
          name: test npm
          command: echo 'we need tests'
